@startuml
skinparam classAttributeIconSize 0
package model.entities {
  class Product {
    - id : Integer
    - name : String
    - category : ProductCategory
    - price : Double
  }
  class Stock {
    + totalProductStockPrice() : Double
    + addNewProduct(product : Product) : void
    + removeProduct(product : Product) : void
    + eraseStock() : void
    + stockIn(product : Product, quantity : Integer) : void
    + stockOut(product : Product, quantity : Integer) :  void
  }
  class ProductItem {
    - product : Product
    - quantity : Integer
    - timeModified : DateTime
  }
}
package model.services {
  class StockFileService {
    - filePath : String
    + loadData() : Stock
    + saveData(stock : Stock) : void
  }
}

package model.enums <<enums>> {
  enum ProductCategory {
    ROUPA
    ELETRONICO
    ESCRITORIO
    COMIDA
    BEBIDA
    HIGIENE_PESSOAL
    LIVRO
  }
}

package application.ui {
    class MenuHandler {
    - drawLine() : void
    + showMenu() : void
    + getOption() : String
  }
}

package application.enums <<enums>> {
  enum MenuOptions {
    LISTAR
    CADASTRAR
    DELETAR
    ADICIONAR
    REMOVER
    SAIR
  }
}

ProductItem --> "1" Product
Stock "1" o-- "-productItems\n0..*" ProductItem
StockFileService ..> Stock
MenuHandler ..> MenuOptions

Product ..> ProductCategory
@enduml
