@startuml
skinparam classAttributeIconSize 0
package model {
  package entities {
    class Product {
      - name : String
      - category : ProductCategory
      - price : Double
      + getProductInfo() : String
    }
    class Inventory {
      + addNewProductItem(productItem : ProductItem) : void
      + removeProductItem(productId : Integer) : void
      + erase() : void
      + in(productId : Integer, quantity : Integer) : void
      + out(productId : Integer, quantity : Integer) :  void
    }
    class ProductItem {
      - id : Integer
      - product : Product
      - quantity : Integer
      - timeModified : DateTime
      + totalValue() : Double
      + getProductItemInfo() : String
      + productsOut(Integer quantity) : void
      + productsIn(Integer quantity) : void
    }
  }
  package services {
      class InventoryFileService {
      - filePath : String
      + loadData() : Inventory
      + saveData(inventory : Inventory) : void
    }
  }
  package enums <<enums>> {
    enum ProductCategory {
      ROUPA
      ELETRONICO
      ESCRITORIO
      COMIDA
      BEBIDA
      HIGIENE_PESSOAL
      LIVRO
    }
  }
}

package application {
  package application.ui {
    class MenuHandler {
    - drawLine() : void
    + showMenu() : void
    }
  }
  package enums <<enums>> {
    enum MenuOptions {
      LISTAR
      CADASTRAR
      DELETAR
      ADICIONAR
      RETIRAR
      SAIR
    }
  }
  package services {
    class UserInputService {
      + getOption() : MenuOptions
      + getProduct() : Product
      + getProductItem() : ProductItem
      + getProductItemId() : Integer
    }
  }
}

ProductItem --> "\t1" Product
Inventory "\t1" o-- "-productItems\n0..*" ProductItem
InventoryFileService ..> Inventory
Product ..> ProductCategory
UserInputService ..> MenuOptions
UserInputService ..> Product
UserInputService ..> ProductItem
@enduml
